[phases.setup]
nixPkgs = ["python3", "ffmpeg", "libGL", "libGLU", "glib"]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",
    "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python main.py"
