[phases.setup]
nixPkgs = ["python3", "ffmpeg", "glib"]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",
    "/opt/venv/bin/pip install -r requirements.txt",
    "/opt/venv/bin/pip install --force-reinstall --no-deps opencv-python-headless==4.9.0.80"
]

[start]
cmd = "/opt/venv/bin/python main.py"
