[phases.setup]
nixPkgs = ["python3", "ffmpeg", "libGL", "libGLU", "glib"]

[phases.install]
cmds = ["python3 -m ensurepip --upgrade", "python3 -m pip install -r requirements.txt"]

[start]
cmd = "python3 main.py"
